{{- range $name, $app := .Values.applications }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" $.Release.Name $name | trunc 63 | trimSuffix "-" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $app.image }}
          ports:
            - containerPort: {{ $app.port }}
---
{{- end }}
