<?php

declare(strict_types=1);

namespace App\Http\Controllers\ExternalIdp;

use App\Actions\ExternalIdp\CreateExternalIdpAuthenticationRedirectAction;
use App\Models\ExternalIdentityProvider;
use App\Services\ExternalIdp\ExternalIdentityProviderRegistry;
use App\Services\ExternalIdp\ExternalIdpAuthenticationRedirectService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Throwable;

/**
 * FR-057 / BE-FR057-001 — public federation start route.
 *
 * Allows end-users to begin authentication with a configured external IdP
 * via a stable URL. The route is opt-in via
 * `sso.external_idp.public_start_route_enabled` so deploy posture stays
 * explicit. When the feature flag is disabled, requests resolve to a 404
 * to avoid leaking provider configuration.
 *
 * Sensitive parameters (return_to, prompt, login_hint) are validated and
 * forwarded to {@see CreateExternalIdpAuthenticationRedirectAction}; the
 * redirect URL is generated by the existing
 * {@see ExternalIdpAuthenticationRedirectService}
 * which enforces HTTPS issuer and authorization endpoints. Failures fall
 * back to the SSO frontend login page so the UI never sees a raw stack.
 */
final class StartExternalIdpAuthenticationController
{
    public function __construct(
        private readonly ExternalIdentityProviderRegistry $registry,
        private readonly CreateExternalIdpAuthenticationRedirectAction $redirects,
    ) {}

    public function __invoke(Request $request, string $providerKey): Response
    {
        if (! $this->enabled()) {
            return $this->loginFallback('external_idp_disabled');
        }

        $provider = ExternalIdentityProvider::query()->where('provider_key', $providerKey)->first();

        if (! $provider instanceof ExternalIdentityProvider || ! $this->registry->isUsable($provider)) {
            return $this->loginFallback('external_idp_unavailable');
        }

        try {
            $redirect = $this->redirects->execute($provider, [
                'request_id' => (string) $request->headers->get('X-Request-Id', ''),
                'ip_address' => (string) $request->ip(),
                'user_agent' => (string) $request->userAgent(),
                'return_to' => $this->safeReturnTo($request),
                'prompt' => $this->stringInput($request, 'prompt'),
                'login_hint' => $this->stringInput($request, 'login_hint'),
            ]);
        } catch (Throwable) {
            return $this->loginFallback('external_idp_redirect_failed');
        }

        return new RedirectResponse($redirect['redirect_url'], 302, [
            'Cache-Control' => 'no-store, no-cache, must-revalidate, private',
            'Pragma' => 'no-cache',
        ]);
    }

    private function enabled(): bool
    {
        return (bool) config('sso.external_idp.public_start_route_enabled', false);
    }

    private function safeReturnTo(Request $request): ?string
    {
        $value = $this->stringInput($request, 'return_to');

        if ($value === null || ! str_starts_with($value, '/')) {
            return null;
        }

        return $value;
    }

    private function stringInput(Request $request, string $key): ?string
    {
        $value = $request->query($key);

        if (! is_string($value)) {
            return null;
        }

        $value = trim($value);

        return $value === '' ? null : $value;
    }

    private function loginFallback(string $reason): RedirectResponse
    {
        $base = rtrim((string) config('sso.login_url', config('sso.frontend_url').'/login'), '/');
        $url = $base.'?'.http_build_query(['error' => $reason]);

        return new RedirectResponse($url, 302, [
            'Cache-Control' => 'no-store, no-cache, must-revalidate, private',
            'Pragma' => 'no-cache',
        ]);
    }
}
