#!/usr/bin/env bash

set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FAILURES=0
WARNINGS=0

pass() {
  printf '[devops-lifecycle][PASS] %s\n' "$*"
}

warn() {
  WARNINGS=$((WARNINGS + 1))
  printf '[devops-lifecycle][WARN] %s\n' "$*" >&2
}

fail() {
  FAILURES=$((FAILURES + 1))
  printf '[devops-lifecycle][FAIL] %s\n' "$*" >&2
}

require_file() {
  local path="$1"
  if [[ -f "$ROOT_DIR/$path" ]]; then
    pass "Found $path"
  else
    fail "Missing $path"
  fi
}

require_dir() {
  local path="$1"
  if [[ -d "$ROOT_DIR/$path" ]]; then
    pass "Found $path"
  else
    fail "Missing $path"
  fi
}

require_text() {
  local file="$1" pattern="$2" label="$3"
  if grep -Eq -- "$pattern" "$ROOT_DIR/$file"; then
    pass "$label"
  else
    fail "$label"
  fi
}

require_workflow_step_text() {
  local file="$1" step="$2" pattern="$3" label="$4"
  if awk -v step="$step" '
    $0 ~ "^[[:space:]]*- name: " step "$" { in_step = 1; next }
    in_step && $0 ~ "^[[:space:]]*- name: " { in_step = 0 }
    in_step { print }
  ' "$ROOT_DIR/$file" | grep -Eq -- "$pattern"; then
    pass "$label"
  else
    fail "$label"
  fi
}

warn_unless_text() {
  local file="$1" pattern="$2" label="$3"
  if grep -Eq -- "$pattern" "$ROOT_DIR/$file"; then
    pass "$label"
  else
    warn "$label"
  fi
}

require_absent_text() {
  local file="$1" pattern="$2" label="$3"
  if grep -Eq -- "$pattern" "$ROOT_DIR/$file"; then
    fail "$label"
  else
    pass "$label"
  fi
}

require_retry_failure_status() {
  local output status
  set +e
  output=$(CI_RETRY_ATTEMPTS=2 CI_RETRY_DELAY_SECONDS=0 \
    "$ROOT_DIR/scripts/ci-retry.sh" bash -lc 'exit 37' 2>&1)
  status=$?
  set -e

  if [[ "$status" -eq 37 ]] && grep -q 'failed with 37' <<<"$output"; then
    pass "CI retry helper preserves non-zero deployment command status"
  else
    fail "CI retry helper preserves non-zero deployment command status"
  fi
}

require_file ".github/workflows/ci.yml"
require_file ".github/workflows/cd.yml"
require_file ".github/workflows/rollback.yml"
require_file ".github/workflows/devops-lifecycle.yml"
require_file ".dockerignore"
require_file ".env.dev.example"
require_file "docker-compose.dev.yml"
require_file "scripts/require-release-ci-success.sh"
require_file "scripts/vps-deploy.sh"
require_file "scripts/wait-for-ghcr-images.sh"
require_file "scripts/vps-login-ui-cutover.sh"
require_file "scripts/vps-rollback.sh"
require_file "scripts/vps-direct-build-deploy.sh"
require_file "scripts/vps-collect-login-flow-logs.sh"
require_file "scripts/vps-apply-sso-efficiency-profile.sh"
require_file "scripts/vps-set-login-api-timeout.sh"
require_file "scripts/vps-pg-stat-statements.sh"
require_file "scripts/ci-retry.sh"
require_file "scripts/lib/app-b-secret-guard.sh"
require_file "scripts/lib/direct-green-prewarm.sh"
require_file "scripts/validate-repository-hygiene.sh"
require_file "scripts/validate-laravel-vue-lifecycle.sh"
require_file "scripts/validate-sso-frontend-vue-lifecycle.sh"
require_file "services/sso-frontend/src/web/styles/auth-shell-floating.css"
require_file "infra/nginx/snippets/id-dev-sso-login-locale-reload.conf"
require_file "infra/nginx/assets/login/parent-chrome.css"
require_file "infra/nginx/assets/login/parent-chrome.js"
require_file "infra/sre/check-coexistence-policy.sh"
require_file "infra/sre/check-identity-resource-policy.sh"
require_file "infra/sre/check-zero-downtime-migration-policy.sh"
require_file "infra/sre/check-observability-assets.sh"
require_file "infra/sre/check-secret-maturity.sh"
require_file "infra/observability/prometheus/prometheus.sso.yml"
require_file "infra/observability/alertmanager/alertmanager.sso.yml"
require_file "infra/observability/grafana/dashboards/sso-control-plane-dashboard.json"
require_file "docs/security/container-image-scanning-policy.md"
require_file "docs/security/refresh-token-checkpoints.md"
require_file "docs/generated/devops-best-practice-validation-2026-04-24.md"
require_file "docs/generated/sso-frontend-vue-rebuild-runbook-2026-04-24.md"
require_file "services/sso-backend/app/Services/Oidc/ClientIntegrationContractBuilder.php"
require_file "services/sso-backend/app/Services/Oidc/ClientIntegrationRegistrationService.php"
require_file "services/sso-backend/app/Services/Oidc/ClientIntegrationRollbackRevoker.php"
require_file "services/sso-backend/app/Models/OidcClientRegistration.php"
require_file "services/sso-backend/app/Support/Oidc/ClientIntegrationDraft.php"
require_file "services/sso-backend/database/migrations/2026_04_28_000001_create_oidc_client_registrations_table.php"
require_file "services/sso-backend/tests/Feature/Admin/AdminClientIntegrationContractTest.php"
require_file "services/sso-backend/tests/Unit/Oidc/ClientIntegrationContractBuilderTest.php"

require_dir "infra/terraform/environments/dev-sso"
require_file "infra/terraform/environments/dev-sso/versions.tf"
require_file "infra/terraform/environments/dev-sso/main.tf"
require_file "infra/terraform/environments/dev-sso/variables.tf"
require_file "infra/terraform/environments/dev-sso/outputs.tf"

require_dir "infra/ansible"
require_file "infra/ansible/ansible.cfg"
require_file "infra/ansible/inventory/dev-sso.ini.example"
require_file "infra/ansible/group_vars/sso_vps.yml"
require_file "infra/ansible/playbooks/devops-preflight.yml"

require_text ".github/workflows/ci.yml" 'permissions:[[:space:]]*$' "CI declares explicit permissions"
require_text ".github/workflows/ci.yml" 'packages: write' "CI image build has package write permission only where needed"
require_text ".github/workflows/ci.yml" 'id-token: write' "CI image build can publish signed provenance"
require_text ".github/workflows/ci.yml" 'attestations: write' "CI image build can publish attestations"
require_text ".github/workflows/ci.yml" 'security-events: write' "CI can upload security scanning evidence"
require_text ".github/workflows/ci.yml" 'FORCE_JAVASCRIPT_ACTIONS_TO_NODE24' "CI opts JavaScript actions into Node 24 runtime"
require_text ".github/workflows/cd.yml" 'FORCE_JAVASCRIPT_ACTIONS_TO_NODE24' "CD opts JavaScript actions into Node 24 runtime"
require_text ".github/workflows/cd.yml" 'actions: read' "CD can read release CI status before deployment"
require_text ".github/workflows/cd.yml" 'VPS_SSH_PORT' "CD supports configurable VPS SSH port"
require_text ".github/workflows/cd.yml" 'Preflight SSH reachability' "CD fails fast when VPS SSH is unreachable"
require_text ".github/workflows/rollback.yml" 'FORCE_JAVASCRIPT_ACTIONS_TO_NODE24' "Rollback opts JavaScript actions into Node 24 runtime"
require_text ".github/workflows/rollback.yml" 'VPS_SSH_PORT' "Rollback supports configurable VPS SSH port"
require_text ".github/workflows/rollback.yml" 'Preflight SSH reachability' "Rollback fails fast when VPS SSH is unreachable"
require_text ".github/workflows/ci.yml" 'actions/checkout@v5' "CI uses Node 24-compatible checkout action"
require_text ".github/workflows/ci.yml" 'actions/setup-node@v6' "CI uses Node 24-compatible setup-node action"
require_text ".github/workflows/ci.yml" 'actions/cache@v5' "CI uses Node 24-compatible cache action"
require_text ".github/workflows/ci.yml" 'docker/build-push-action@v7' "CI uses Docker Buildx build-push action"
require_text ".dockerignore" '\*\*/node_modules' "Docker root context excludes Node dependencies"
require_text ".dockerignore" '\*\*/node_modules\*' "Docker root context excludes copied Node dependency snapshots"
require_text ".dockerignore" '\*\*/node_modules\.\*' "Docker root context excludes dependency snapshots"
require_text ".dockerignore" '\*\*/\*\.zip' "Docker root context excludes local ZIP archives"
require_text ".gitignore" 'apps/\*/node_modules\*' "Git ignores copied app dependency snapshots"
require_text ".gitignore" 'services/\*/node_modules\*' "Git ignores copied service dependency snapshots"
require_text ".gitignore" '^\*\.zip$' "Git ignores local ZIP archives"
require_text ".dockerignore" '\.secrets' "Docker root context excludes local secrets"
require_text ".github/workflows/ci.yml" 'docker/metadata-action@v6' "CI uses Docker metadata action"
require_text ".github/workflows/ci.yml" 'storage/framework/views' "CI prepares Laravel runtime directories for ephemeral runners"
require_text ".github/workflows/ci.yml" 'cache-to: type=gha' "CI uses Docker build cache"
require_text ".github/workflows/ci.yml" 'sbom: true' "CI emits container SBOM attestations"
require_text ".github/workflows/ci.yml" 'provenance: mode=max' "CI emits max provenance attestations"
require_text ".github/workflows/ci.yml" 'anchore/scan-action@[0-9a-f]{40}' "CI runs a SHA-pinned Grype CVE scan"
require_text ".github/workflows/ci.yml" 'fail-build: true' "CI blocks high/critical fixable container vulnerabilities"
require_text ".github/workflows/ci.yml" 'Require Grype SARIF evidence' "CI fails when the vulnerability scanner does not produce evidence"
require_text ".github/workflows/ci.yml" 'only-fixed: true' "CI scopes image CVE evidence to fixable vulnerabilities"
require_text ".github/workflows/ci.yml" 'github/codeql-action/upload-sarif@v4' "CI uploads container scan SARIF evidence"
require_absent_text ".github/workflows/ci.yml" 'docker/scout-action|Docker Scout|DOCKERHUB_TOKEN|dockerhub-' "CI no longer depends on Docker Scout entitlement"
require_text ".github/workflows/ci.yml" 'sso-admin-vue' "CI builds Vue admin canary image"

require_text ".github/workflows/cd.yml" 'environment: production' "CD requires production environment gate"
require_text ".github/workflows/cd.yml" 'cancel-in-progress: false' "CD does not cancel in-flight deployments"
require_text ".github/workflows/cd.yml" 'docker-compose\.dev\.yml' "CD syncs Compose control-plane file"
require_text ".github/workflows/cd.yml" 'scripts/vps-deploy\.sh' "CD syncs VPS deploy script"
require_text ".github/workflows/cd.yml" 'scripts/vps-apply-edge-config\.sh' "CD syncs VPS edge config apply script"
require_text ".github/workflows/cd.yml" 'scripts/vps-login-ui-cutover\.sh' "CD syncs VPS login UI cutover script"
require_text ".github/workflows/cd.yml" 'scripts/vps-rollback\.sh' "CD syncs VPS rollback script"
require_text ".github/workflows/cd.yml" 'scripts/lib' "CD syncs shared deploy guard library"
require_text ".github/workflows/cd.yml" 'infra/nginx/' "CD syncs Nginx edge config with the release"
require_text ".github/workflows/cd.yml" 'sudo install -m 0644 /tmp/_deploy_bundle/docker-compose\.dev\.yml' "CD installs Compose control plane atomically"
require_text ".github/workflows/cd.yml" 'Apply edge reverse proxy config' "CD applies Nginx edge config before service rollout"
require_text ".github/workflows/cd.yml" 'scripts/lib/app-b-secret-guard\.sh' "CD installs shared App B secret guard library"
require_text ".github/workflows/cd.yml" 'scripts/lib/direct-green-prewarm\.sh' "CD installs shared direct-deploy green prewarm library"
require_text ".github/workflows/cd.yml" 'docker/login-action@v4' "CD authenticates to GHCR before artifact preflight"
require_text ".github/workflows/cd.yml" 'scripts/wait-for-ghcr-images\.sh' "CD waits for release image manifests before VPS deploy"
require_text ".github/workflows/cd.yml" 'Require successful release CI' "CD gates deployment on release CI success"
require_text ".github/workflows/cd.yml" 'scripts/require-release-ci-success\.sh' "CD invokes the release CI status gate"
require_text ".github/workflows/cd.yml" 'CI_RETRY_ATTEMPTS="1"' "CD does not retry the non-idempotent VPS deploy after rollback"
require_text "scripts/require-release-ci-success.sh" 'gh run list' "Release CI gate queries GitHub Actions run status"
require_text "scripts/require-release-ci-success.sh" 'Release CI did not pass before deployment' "Release CI gate blocks failed release CI"
require_retry_failure_status

require_text ".github/workflows/rollback.yml" 'workflow_dispatch' "Rollback is manually dispatchable"
require_text ".github/workflows/rollback.yml" 'target_tag' "Rollback requires an explicit target tag"
require_text ".github/workflows/rollback.yml" 'scripts/vps-rollback\.sh' "Rollback workflow executes rollback script"
require_text ".github/workflows/rollback.yml" 'scripts/lib' "Rollback workflow syncs shared deploy guard library"
require_text ".github/workflows/rollback.yml" 'login_ui' "Rollback workflow can choose hosted or Vue login UI"
require_text ".github/workflows/rollback.yml" 'vps-login-ui-cutover\.sh' "Rollback workflow applies login UI rollback policy"
require_text ".github/workflows/vps-maintenance.yml" 'VPS_SSH_PORT' "VPS maintenance supports configurable SSH port"
require_text ".github/workflows/vps-maintenance.yml" 'Preflight SSH reachability' "VPS maintenance fails fast when SSH is unreachable"
require_text ".github/workflows/vps-maintenance.yml" 'audit-sso-runtime-policy' "VPS maintenance can audit live SSO runtime resource policy"
require_text ".github/workflows/vps-maintenance.yml" 'apply-sso-runtime-policy' "VPS maintenance can apply live SSO runtime resource policy without restart"
require_text ".github/workflows/vps-maintenance.yml" 'vps-update-sso-runtime-budget\.sh' "VPS maintenance delegates resource reconciliation to the guarded runtime budget script"
require_text ".github/workflows/vps-maintenance.yml" 'diagnose-sso-performance' "VPS maintenance can run SSO performance diagnostics"
require_text ".github/workflows/vps-maintenance.yml" 'vps-diagnose-sso-performance\.sh' "VPS maintenance syncs the SSO performance diagnostic script"
require_text ".github/workflows/vps-maintenance.yml" '\$\{\{ env\.VPS_PROJECT_DIR \}\}/scripts/vps-diagnose-sso-performance\.sh' "VPS maintenance runs diagnostics from the project script path"
require_text ".github/workflows/vps-maintenance.yml" 'apply-sso-efficiency-profile' "VPS maintenance can apply the lean SSO runtime profile"
require_text ".github/workflows/vps-maintenance.yml" 'vps-apply-sso-efficiency-profile\.sh' "VPS maintenance delegates SSO efficiency changes to the guarded script"
require_workflow_step_text ".github/workflows/vps-maintenance.yml" "Apply SSO efficiency profile" 'CI_RETRY_ATTEMPTS="1" CI_RETRY_DELAY_SECONDS="0"' "VPS maintenance does not retry non-idempotent efficiency apply"
require_workflow_step_text ".github/workflows/vps-maintenance.yml" "Apply SSO efficiency profile" '--recreate-data-plane false' "VPS maintenance does not restart PostgreSQL/Redis during app-plane efficiency incidents"
require_workflow_step_text ".github/workflows/vps-maintenance.yml" "Apply SSO efficiency profile" '--compose-up-timeout-seconds 240' "VPS maintenance bounds each service recreate to avoid hung incident pipelines"
require_workflow_step_text ".github/workflows/vps-maintenance.yml" "Apply SSO efficiency profile" '--health-timeout-seconds 300' "VPS maintenance bounds each service health wait with a wall-clock budget"
require_text ".github/workflows/vps-maintenance.yml" 'audit-pg-stat-statements' "VPS maintenance can audit PostgreSQL hot-query observability"
require_text ".github/workflows/vps-maintenance.yml" 'enable-pg-stat-statements-extension' "VPS maintenance can enable PostgreSQL hot-query extension after preload"
require_text ".github/workflows/vps-maintenance.yml" 'vps-pg-stat-statements\.sh' "VPS maintenance delegates pg_stat_statements lifecycle to the guarded script"
require_text ".github/workflows/vps-maintenance.yml" 'collect-login-flow-logs' "VPS maintenance can collect live login-flow logs"
require_text ".github/workflows/vps-maintenance.yml" 'vps-collect-login-flow-logs\.sh' "VPS maintenance delegates login-flow log collection to the guarded script"
require_text ".github/workflows/vps-maintenance.yml" 'set-login-api-timeout' "VPS maintenance can adjust Vue login upstream timeout during pressure incidents"
require_text ".github/workflows/vps-maintenance.yml" 'vps-set-login-api-timeout\.sh' "VPS maintenance delegates login timeout changes to the guarded script"
require_text ".github/workflows/vps-maintenance.yml" 'stop-noncritical-container' "VPS maintenance can stop whitelisted non-critical containers"
require_text ".github/workflows/vps-maintenance.yml" 'vps-stop-noncritical-container\.sh' "VPS maintenance delegates non-critical stops to the guarded script"

require_text "docker-compose.dev.yml" 'sso-admin-vue:' "Compose defines Vue canary service"
require_text "docker-compose.dev.yml" 'http://127\.0\.0\.1:3000/ui/v2/login/healthy' "Hosted ZITADEL login healthcheck uses lightweight health endpoint"
require_text "docker-compose.dev.yml" 'http://127\.0\.0\.1:3000/healthz' "App A healthcheck prefers dedicated health endpoint"
require_text "docker-compose.dev.yml" 'http://127\.0\.0\.1:3000 >/dev/null' "App A healthcheck preserves one-release rollback fallback"
require_absent_text "docker-compose.dev.yml" 'npm run start -- --hostname 0\.0\.0\.0 --port 3000' "App A production container uses standalone Node runtime without npm"
require_text "docker-compose.dev.yml" 'HOSTNAME: 0\.0\.0\.0' "App A standalone runtime binds to all interfaces for health-gated deploys"
require_text "services/sso-frontend/src/server/session.ts" 'absoluteExpiresAt' "SSO Admin enforces absolute session timeout"
require_text "services/sso-frontend/src/server/config.ts" 'ADMIN_SESSION_IDLE_TTL_SECONDS' "SSO Admin exposes idle session timeout"
require_text "services/sso-frontend/src/server/config.ts" 'ADMIN_FRESH_AUTH_TTL_SECONDS' "SSO Admin exposes fresh-auth timeout"
require_text "services/sso-frontend/src/web/stores/admin.ts" 'devsso-admin-refresh' "SSO Admin single-flights browser refresh"
require_text "services/sso-frontend/scripts/check-wcag-theme.mjs" 'admin ink on sidebar' "SSO Admin WCAG gate covers sidebar contrast"
require_text "services/sso-frontend/src/web/components/ClientIntegrationProcedure.vue" 'RFC 7642 onboarding' "SSO Admin exposes RFC 7642 client onboarding procedure"
require_text "services/sso-frontend/src/web/components/ClientIntegrationProcedure.vue" 'Client stitching wizard' "SSO Admin exposes client stitching wizard"
require_text "services/sso-frontend/src/web/components/ClientIntegrationProcedure.vue" 'Validasi via broker' "SSO Admin can request broker-authoritative client validation"
require_text "services/sso-frontend/src/web/components/ClientIntegrationProcedure.vue" 'Registry patch' "SSO Admin exposes auditable registry patch artifacts"
require_text "services/sso-frontend/src/web/components/ClientProvisioningReadiness.vue" 'Provisioning readiness' "SSO Admin exposes RFC 7642 provisioning readiness artifacts"
require_text "services/sso-frontend/src/web/components/ClientIntegrationRegistrations.vue" 'Dynamic registrations' "SSO Admin shows dynamic client registration lifecycle"
require_text "services/sso-frontend/src/web/components/ClientIntegrationRegistrations.vue" 'Stage registration' "SSO Admin can stage client registration artifacts"
require_text "services/sso-frontend/src/web/components/ClientIntegrationRegistrations.vue" 'Rollback / disable' "SSO Admin can rollback staged or active client registrations"
require_text "services/sso-frontend/src/shared/client-integration.ts" 'validateClientIntegrationDraft' "SSO Admin validates client stitching metadata"
require_text "services/sso-frontend/src/shared/client-integration.ts" 'Base URL hanya boleh berisi origin tanpa path, query, atau fragment' "SSO Admin rejects non-canonical client origins"
require_text "services/sso-frontend/src/shared/client-integration.ts" 'tidak boleh mengandung traversal' "SSO Admin rejects path traversal in client contract paths"
require_text "services/sso-frontend/src/shared/client-integration.ts" 'SSO_CLIENT_SECRET=<store-in-vault>' "SSO Admin keeps confidential client secrets out of the browser"
require_text "services/sso-frontend/src/shared/client-integration.ts" 'registryPatch' "SSO Admin contract includes registry patch output"
require_text "services/sso-frontend/src/shared/client-integration.ts" 'provisioningManifest' "SSO Admin contract includes provisioning readiness output"
require_text "services/sso-backend/routes/admin.php" '/client-integrations/contract' "SSO backend exposes protected client integration contract endpoint"
require_text "services/sso-backend/routes/admin.php" '/client-integrations/stage' "SSO backend exposes protected dynamic client staging endpoint"
require_text "services/sso-backend/routes/admin.php" '/client-integrations/\{clientId\}/activate' "SSO backend exposes protected dynamic client activation endpoint"
require_text "services/sso-backend/routes/admin.php" '/client-integrations/\{clientId\}/disable' "SSO backend exposes protected dynamic client rollback endpoint"
require_text "services/sso-backend/app/Services/Oidc/DownstreamClientRegistry.php" 'Schema::hasTable' "SSO broker guards dynamic registry during zero-downtime migration"
require_text "services/sso-backend/app/Services/Oidc/ClientIntegrationContractBuilder.php" 'Client ID sudah terdaftar di broker' "SSO backend rejects duplicate client registration"
require_text "services/sso-backend/app/Services/Oidc/ClientIntegrationContractBuilder.php" 'Redirect URI sudah dipakai client lain' "SSO backend rejects redirect URI reuse"
require_text "services/sso-backend/app/Services/Oidc/ClientIntegrationContractBuilder.php" 'Base URL tidak boleh memuat credentials' "SSO backend rejects credentialed client origins"
require_text "services/sso-backend/app/Services/Oidc/ClientIntegrationContractBuilder.php" 'tidak boleh diawali //' "SSO backend rejects scheme-relative callback paths"
require_text "services/sso-backend/app/Support/Oidc/ClientUrlOrigin.php" 'port === 443' "SSO backend canonicalizes default HTTPS ports for exact redirect matching"
require_text "services/sso-backend/app/Services/Oidc/ClientIntegrationContractBuilder.php" 'SSO_CLIENT_SECRET=<store-in-vault>' "SSO backend keeps confidential client secrets in vault handoff"
require_text "services/sso-backend/app/Services/Oidc/ClientProvisioningReadinessBuilder.php" 'SCIM active=false disables local account before next login' "SSO backend builds RFC 7642 deprovisioning readiness contract"
require_text "services/sso-backend/app/Services/Oidc/ClientIntegrationRegistrationService.php" 'ClientIntegrationRollbackRevoker' "SSO backend rollback disables clients through a dedicated revoker"
require_text "services/sso-backend/app/Services/Oidc/ClientIntegrationRollbackRevoker.php" 'revokeClient' "SSO backend rollback revokes client refresh and access token indexes"
require_text "services/sso-backend/app/Services/Oidc/ClientIntegrationRollbackRevoker.php" 'backchannel_fanout' "SSO backend rollback queues client-specific back-channel logout fanout"
require_text "services/sso-backend/app/Services/Oidc/AccessTokenGuard.php" 'unknown_client' "SSO backend rejects access tokens for inactive clients"
require_text "services/sso-backend/app/Services/Oidc/AccessTokenRevocationStore.php" 'clientKey' "SSO backend tracks access token revocation by client"
require_text "services/sso-backend/app/Services/Oidc/RefreshTokenStore.php" 'public function revokeClient' "SSO backend can revoke refresh-token families by client"
require_text "services/sso-frontend/src/__tests__/client-integration-contract.test.ts" 'confidential SCIM' "SSO Admin tests confidential SCIM client contracts"
require_text "services/sso-frontend/src/__tests__/client-integration-contract.test.ts" 'non-canonical origins' "SSO Admin tests exact redirect URI safety"
require_text "services/sso-backend/tests/Feature/Admin/AdminClientIntegrationContractTest.php" 'without mutating broker clients' "SSO backend tests readonly client integration contract validation"
require_text "services/sso-backend/tests/Feature/Admin/AdminClientIntegrationContractTest.php" 'path confusion' "SSO backend tests client contract path confusion rejection"
require_text "services/sso-backend/tests/Feature/Admin/AdminClientIntegrationContractTest.php" 'jti-rollback' "SSO backend tests dynamic client rollback revokes active access tokens"
require_text "services/sso-backend/tests/Unit/Oidc/AccessTokenGuardTest.php" 'client is not active' "SSO backend tests inactive client token rejection"
require_text "services/sso-frontend/src/web/views/DashboardView.vue" 'ClientIntegrationProcedure' "SSO Admin dashboard renders client onboarding procedure"
require_text "docs/generated/client-integration-rfc7642-runbook-2026-04-28.md" 'Client Integration Runbook RFC 7642' "Docs capture RFC 7642 client integration runbook"
require_text "docs/generated/client-integration-rfc7642-runbook-2026-04-28.md" 'Feature Logic Admin Panel' "Docs capture dashboard stitching feature logic"
require_text "docs/generated/client-integration-rfc7642-runbook-2026-04-28.md" 'Pola SSO multi-client' "Docs capture Google-style multi-client SSO audit principles"
require_text "docs/generated/client-integration-rfc7642-runbook-2026-04-28.md" 'TDD Whole Source Audit' "Docs capture whole-source TDD audit expansion"
require_text "docker-compose.dev.yml" 'http://127\.0\.0\.1:8000/health' "App B healthcheck avoids SSO redirect code paths"
require_text "docker-compose.dev.yml" 'image: sso-dev-sso-admin-vue:\$\{APP_IMAGE_TAG:-local\}' "Vue canary image is tag-addressable"
require_text "docker-compose.dev.yml" 'PathPrefix\(`\$\{SSO_ADMIN_VUE_BASE_PATH:-/__vue-preview\}`\)' "Vue canary route is path-isolated"
require_text "docker-compose.dev.yml" 'traefik.http.routers.sso-backend.priority=200' "Backend API/OIDC keeps highest router priority"
require_text "docker-compose.dev.yml" 'traefik.http.routers.sso-admin-vue.priority=175' "Vue canary priority stays below backend"
require_text "docker-compose.dev.yml" 'traefik.http.routers.sso-frontend.priority=50' "Current frontend root catch-all stays lower priority"
require_text ".env.dev.example" '^SSO_ADMIN_VUE_BASE_PATH=/__vue-preview$' "Development env example exposes Vue canary base path"
require_text ".env.dev.example" '^APP_A_SESSION_COOKIE_NAME=__Host-app-a-session$' "App A env example uses hardened __Host cookie prefix"
require_text ".env.dev.example" '^ADMIN_SESSION_IDLE_TTL_SECONDS=604800$' "Development env exposes SSO Admin idle TTL"
require_text ".env.dev.example" '^ADMIN_SESSION_ABSOLUTE_TTL_SECONDS=2592000$' "Development env exposes SSO Admin absolute TTL"
require_text ".env.dev.example" '^QUEUE_CONNECTION=redis$' "Development env moves queue polling away from PostgreSQL"
require_text ".env.dev.example" '^SSO_BACKEND_OCTANE_WORKERS=1$' "Development env caps Laravel Octane workers for the 2-vCPU SSO host"
require_text ".env.dev.example" '^SSO_BACKEND_QUEUE_WORKERS=1$' "Development env pins Laravel queue worker count for CPU recovery"
require_text ".env.dev.example" '^SSO_BACKEND_QUEUE_SLEEP_SECONDS=10$' "Development env throttles idle queue polling pressure"
require_text "docker-compose.dev.yml" 'x-auth-web-limits' "Compose grants the identity login path a dedicated web resource budget"
require_text "docker-compose.dev.yml" 'ZITADEL_TELEMETRY_ENABLED: "false"' "Compose disables ZITADEL telemetry ping for the internal SSO runtime"
require_text "docker-compose.dev.yml" 'ZITADEL_SERVICEPING_ENABLED: "false"' "Compose disables ZITADEL service ping retry jobs"
require_text "docker-compose.dev.yml" 'ZITADEL_SERVICE_PING_ENABLED: "false"' "Compose disables alternate ZITADEL service ping env spelling"
require_text "docker-compose.dev.yml" 'dns:[[:space:]]*$' "Compose declares explicit DNS fallback for ZITADEL"
require_text "docker-compose.dev.yml" '8\.8\.8\.8' "Compose gives ZITADEL Google DNS fallback"
require_text "docker-compose.dev.yml" '1\.1\.1\.1' "Compose gives ZITADEL Cloudflare DNS fallback"
require_text "docker-compose.dev.yml" 'shared_preload_libraries=pg_stat_statements' "Compose prepares PostgreSQL hot-query statistics preload for planned restart"
require_text "docker-compose.dev.yml" 'pg_stat_statements.track=all' "Compose tracks all PostgreSQL statements for hot-query analysis"
require_text "docker-compose.dev.yml" 'SSO_BACKEND_OCTANE_WORKERS: \$\{SSO_BACKEND_OCTANE_WORKERS:-1\}' "Compose exposes Laravel Octane worker budget"
require_text "docker-compose.dev.yml" 'opcache\.jit=off' "Compose disables PHP JIT for CPU-constrained Laravel runtimes"
require_text "docker-compose.dev.yml" 'REDIS_PASSWORD: \$\{REDIS_PASSWORD\}' "Compose exposes Redis auth only to the Redis container healthcheck"
require_text "services/sso-backend/Dockerfile" 'SSO_BACKEND_OCTANE_WORKERS=(1|auto)|--workers=\$\{SSO_BACKEND_OCTANE_WORKERS:-1\}' "SSO backend image exposes bounded Octane worker configuration"
require_text "services/sso-backend/Dockerfile" 'opcache\.jit=off' "SSO backend image disables PHP JIT for OLTP-style auth traffic"
require_absent_text "services/sso-backend/Dockerfile" '--workers=4' "SSO backend image no longer hardcodes four Octane workers"
require_text "infra/nginx/dev-sso.timeh.my.id.chained.conf" 'sso_zitadel_login_api_per_ip' "Nginx rate limits expensive Vue login API calls"
require_text "infra/nginx/dev-sso.timeh.my.id.chained.conf" '/ui/v2/auth/assets/' "Nginx preserves immutable cache policy for Vue login assets"
require_text "infra/nginx/dev-sso.timeh.my.id.chained.conf" 'upstream sso_traefik_web' "Nginx edge config declares a canonical Traefik upstream"
require_text "infra/nginx/dev-sso.timeh.my.id.chained.conf" 'keepalive 64;' "Nginx edge config keeps Traefik upstream connections warm"
require_text "infra/nginx/snippets/sso-auth-sensitive-proxy.conf" 'proxy_pass http://sso_traefik_web;' "Nginx auth-sensitive proxy uses the canonical Traefik upstream"
require_text "scripts/vps-apply-edge-config.sh" 'nginx -t' "Edge config apply validates Nginx before reload"
require_text "scripts/vps-apply-edge-config.sh" 'restore_previous' "Edge config apply restores previous Nginx config on validation failure"
require_text "scripts/vps-apply-edge-config.sh" 'disable_stale_site_configs' "Edge config apply removes stale enabled host configs before validation"
require_text "scripts/vps-apply-edge-config.sh" 'disable_conflicting_sso_configs' "Edge config apply removes renamed legacy SSO site configs before validation"
require_text "scripts/vps-apply-edge-config.sh" 'nginx_includes_sites_available' "Edge config apply avoids duplicate site loads on non-standard Nginx include layouts"
require_text "scripts/vps-diagnose-sso-performance.sh" 'docker stats --no-stream' "VPS diagnostic captures container CPU and memory snapshot"
require_text "scripts/vps-diagnose-sso-performance.sh" 'Host top CPU processes' "VPS diagnostic captures host CPU process pressure"
require_text "scripts/vps-diagnose-sso-performance.sh" 'Focused SSO container samples' "VPS diagnostic samples SSO container CPU pressure repeatedly"
require_text "scripts/vps-diagnose-sso-performance.sh" 'pg_stat_activity' "VPS diagnostic captures PostgreSQL connection activity"
require_text "scripts/vps-diagnose-sso-performance.sh" 'ZITADEL container audit' "VPS diagnostic captures ZITADEL container health and restart state"
require_text "scripts/vps-diagnose-sso-performance.sh" '/debug/metrics' "VPS diagnostic samples ZITADEL metrics without exposing them publicly"
require_text "scripts/vps-diagnose-sso-performance.sh" 'x-zitadel-instance-host' "VPS diagnostic probes ZITADEL with canonical instance headers"
require_text "scripts/vps-diagnose-sso-performance.sh" 'pg_locks' "VPS diagnostic captures PostgreSQL lock pressure"
require_text "scripts/vps-diagnose-sso-performance.sh" 'pg_stat_statements hot queries' "VPS diagnostic attempts PostgreSQL hot-query analysis"
require_text "scripts/vps-diagnose-sso-performance.sh" 'pg_stat_statements unavailable' "VPS diagnostic explains missing PostgreSQL hot-query extension"
require_text "scripts/vps-diagnose-sso-performance.sh" 'Proxy recent pressure' "VPS diagnostic captures reverse-proxy pressure indicators"
require_text "scripts/vps-diagnose-sso-performance.sh" 'Redis pressure' "VPS diagnostic captures Redis command and eviction pressure"
require_text "scripts/vps-diagnose-sso-performance.sh" 'REDISCLI_AUTH' "VPS diagnostic authenticates Redis probes without printing credentials"
require_text "scripts/vps-diagnose-sso-performance.sh" 'compose exec -T -e REDISCLI_AUTH' "VPS diagnostic injects Redis auth from the env file instead of trusting container env"
require_text "scripts/vps-diagnose-sso-performance.sh" 'redact_sensitive' "VPS diagnostic redacts sensitive ZITADEL log fields"
require_text "scripts/vps-update-sso-runtime-budget.sh" 'MODE="audit"' "Runtime budget script defaults to read-only audit mode"
require_text "scripts/vps-update-sso-runtime-budget.sh" 'docker update' "Runtime budget script can reconcile budgets without restarting containers"
require_text "scripts/vps-update-sso-runtime-budget.sh" 'Rollback file:' "Runtime budget script emits a rollback file path"
require_text "scripts/vps-update-sso-runtime-budget.sh" 'sso-backend-worker' "Runtime budget script covers SSO backend worker pressure"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'MODE="audit"' "SSO efficiency script defaults to read-only audit mode"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'TELESCOPE_ENABLED=false' "SSO efficiency script disables debug observers on the live path"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'QUEUE_CONNECTION=redis' "SSO efficiency script moves queue polling away from PostgreSQL"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'SSO_BACKEND_QUEUE_WORKERS=1' "SSO efficiency script pins Laravel queue workers for CPU recovery"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'SSO_BACKEND_QUEUE_SLEEP_SECONDS=10' "SSO efficiency script throttles idle queue polling pressure"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'SSO_BACKEND_OCTANE_WORKERS=1' "SSO efficiency script right-sizes Laravel Octane worker count"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'RECREATE_DATA_PLANE="false"' "SSO efficiency script keeps data-plane restarts opt-in"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'COMPOSE_UP_TIMEOUT_SECONDS=240' "SSO efficiency script bounds Docker Compose recreates"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'HEALTH_TIMEOUT_SECONDS=300' "SSO efficiency script gives slow app services a bounded health window"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'timeout "\$COMPOSE_UP_TIMEOUT_SECONDS" docker compose' "SSO efficiency script fails fast on stuck service recreates"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'elapsed=\$\(\(now - start\)\)' "SSO efficiency script uses wall-clock health timeouts under Docker pressure"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'docker tag "\$image_id" "\$image"' "SSO efficiency script can recreate running services without building on the VPS"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'stop_service_if_running "app-b-laravel"' "SSO efficiency script can stop demo clients outside the primary login path"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" '--no-build --pull never' "SSO efficiency script never builds images on the pressured VPS"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'RELEASE_TAG_FILE="/tmp/\.sso-deploy-rollback-tag"' "SSO efficiency script reuses the current release image tag"
require_text "scripts/vps-apply-sso-efficiency-profile.sh" 'Rollback' "SSO efficiency script prints rollback guidance"
require_text "scripts/vps-pg-stat-statements.sh" 'MODE="audit"' "PostgreSQL hot-query script defaults to read-only audit mode"
require_text "scripts/vps-pg-stat-statements.sh" 'show shared_preload_libraries' "PostgreSQL hot-query script verifies preload status before mutation"
require_text "scripts/vps-pg-stat-statements.sh" 'create extension if not exists pg_stat_statements' "PostgreSQL hot-query script can enable the extension idempotently"
require_text "scripts/vps-pg-stat-statements.sh" 'Refusing to create pg_stat_statements' "PostgreSQL hot-query script refuses unsafe enablement before preload"
require_text "scripts/vps-pg-stat-statements.sh" 'redact_sensitive' "PostgreSQL hot-query script redacts sensitive query samples"
require_text "scripts/vps-collect-login-flow-logs.sh" 'set -Eeuo pipefail' "Login-flow log collector is shell strict and operator-driven"
require_text "scripts/vps-collect-login-flow-logs.sh" 'session/password' "Login-flow log collector filters password-step failures without printing credentials"
require_text "scripts/vps-collect-login-flow-logs.sh" 'redact_sensitive' "Login-flow log collector redacts identity log output"
require_text "scripts/vps-set-login-api-timeout.sh" 'BACKUP_FILE' "Login timeout script snapshots env before live change"
require_text "scripts/vps-set-login-api-timeout.sh" 'docker tag "\$image_id" "\$image_ref"' "Login timeout script preserves the running image tag before no-build recreate"
require_text "scripts/vps-set-login-api-timeout.sh" 'probe_path "vue_login_health"' "Login timeout script waits for reverse-proxy health readiness"
require_text "scripts/vps-set-login-api-timeout.sh" 'Rollback' "Login timeout script prints rollback guidance"
require_text "scripts/vps-stop-noncritical-container.sh" 'n8n-n8n-1' "Non-critical stop script only allows approved containers"
require_text "scripts/vps-stop-noncritical-container.sh" 'Refusing to stop non-whitelisted container' "Non-critical stop script refuses unapproved targets"
require_text "scripts/vps-stop-noncritical-container.sh" 'Rollback command: docker start' "Non-critical stop script prints rollback guidance"

require_text "scripts/vps-deploy.sh" 'export APP_IMAGE_TAG="\$TAG"' "Deploy exports deterministic APP_IMAGE_TAG"
require_text "scripts/wait-for-ghcr-images.sh" 'docker manifest inspect' "CD artifact gate verifies GHCR manifests deterministically"
require_text "scripts/wait-for-ghcr-images.sh" 'app-b-laravel' "CD artifact gate covers downstream Laravel app image"
require_text "scripts/vps-deploy.sh" 'compose config --services' "Deploy preflights Compose services"
require_text "scripts/vps-deploy.sh" 'CONTROL_PLANE_SERVICES=\(zitadel-api\)' "Deploy reconciles ZITADEL runtime config when Compose changes"
require_text "scripts/vps-deploy.sh" 'restore_compose_backup' "Deploy restores previous Compose control plane before rollback"
require_text "scripts/vps-deploy.sh" 'rollback_control_plane_services' "Deploy re-applies previous ZITADEL control-plane config during rollback"
require_text "scripts/vps-deploy.sh" 'functional_ready' "Deploy has service-specific functional readiness fallback"
require_text "docker-compose.dev.yml" '/debug/ready' "ZITADEL healthcheck uses documented readiness endpoint"
require_text "scripts/vps-deploy.sh" 'app_b_require_confidential_client_ready "deploy"' "Deploy invokes shared App B confidential client guard"
require_text "scripts/lib/app-b-secret-guard.sh" 'prevent Compose dollar interpolation' "Shared guard blocks raw dollar-interpolated App B secret hashes"
require_text "scripts/lib/app-b-secret-guard.sh" 'APP_B_CLIENT_SECRET_HASH must verify APP_B_CLIENT_SECRET before \$\{purpose\}' "Shared guard blocks mismatched App B deploy credentials"
require_text "scripts/vps-deploy.sh" 'sso-admin-vue' "Deploy includes Vue admin canary"
require_text "scripts/vps-deploy.sh" 'ZITADEL Hosted Login' "Registry deploy smokes deterministic hosted-login health"
require_text "scripts/vps-deploy.sh" 'App A Health' "Registry deploy smokes deterministic App A health endpoint"
require_text "scripts/vps-deploy.sh" 'App B Health' "Registry deploy smokes deterministic App B health endpoint"
require_text "scripts/vps-deploy.sh" '--resolve "\$host:443:127\.0\.0\.1"' "Registry deploy smokes HTTPS through the local reverse proxy"
require_text "scripts/vps-deploy.sh" 'SMOKE_RETRIES' "Registry deploy retries transient reverse-proxy smoke checks"
require_text "scripts/vps-deploy.sh" 'SMOKE_FAILED=0' "Deploy treats smoke failures as rollback triggers"
require_text "scripts/vps-deploy.sh" 'vps-rollback\.sh' "Deploy can call rollback script"
require_text "scripts/vps-login-ui-cutover.sh" '--mode must be vue or hosted' "Login UI cutover validates the requested mode"
require_text "scripts/vps-login-ui-cutover.sh" 'Vue login canary' "Login UI cutover smokes Vue login canary path"
require_text "scripts/vps-rollback.sh" 'export APP_IMAGE_TAG="\$TAG"' "Rollback exports deterministic APP_IMAGE_TAG"
require_text "scripts/vps-rollback.sh" 'compose config --services' "Rollback preflights Compose services"
require_text "scripts/vps-rollback.sh" 'app_b_require_confidential_client_ready "rollback"' "Rollback invokes shared App B confidential client guard"
require_text "scripts/lib/app-b-secret-guard.sh" 'APP_B_CLIENT_SECRET_HASH must verify APP_B_CLIENT_SECRET before \$\{purpose\}' "Shared guard blocks mismatched App B rollback credentials"
require_text "scripts/set-app-b-hash.sh" "APP_B_CLIENT_SECRET_HASH stored as quoted Argon2id literal" "App B hash rotation stores Compose-safe literals"
require_text "scripts/set-app-b-hash.sh" "Default plaintext: current APP_B_CLIENT_SECRET" "App B hash rotation defaults to the deployed client secret"
require_absent_text "scripts/set-app-b-hash.sh" 'Generated: \$HASH|grep APP_B_CLIENT_SECRET_HASH' "App B hash rotation does not print secret material"
require_absent_text ".github/workflows/vps-maintenance.yml" 'grep APP_B_CLIENT_SECRET_HASH|grep OIDC_CLIENT_SECRET_HASH' "VPS maintenance workflow does not print secret material"
require_text "scripts/vps-direct-build-deploy.sh" 'docker build --pull' "Direct VPS deploy builds immutable local images without Compose dependency rebuilds"
require_text "scripts/vps-direct-build-deploy.sh" 'app-a-next\)' "Direct VPS deploy can rebuild App A"
require_text "scripts/vps-direct-build-deploy.sh" 'app-b-laravel\)' "Direct VPS deploy can rebuild App B"
require_text "scripts/vps-direct-build-deploy.sh" 'App A Health' "Direct VPS deploy smokes App A health"
require_text "scripts/vps-direct-build-deploy.sh" 'App B Health' "Direct VPS deploy smokes App B health"
require_text "scripts/vps-direct-build-deploy.sh" 'VITE_SSO_BASE_URL' "Direct VPS deploy passes frontend build args explicitly"
require_text "scripts/vps-direct-build-deploy.sh" 'ROLLBACK_TAG="rollback-\$\{TAG\}"' "Direct VPS deploy creates rollback image tag"
require_text "scripts/vps-direct-build-deploy.sh" 'rollback_once "Deploy failed unexpectedly"' "Direct VPS deploy runs rollback once on failure"
require_text "scripts/vps-direct-build-deploy.sh" 'TOUCHED_SERVICES\+=\("\$svc"\)' "Direct VPS deploy rolls back only services touched at runtime"
require_text "scripts/vps-direct-build-deploy.sh" 'wait_healthy "\$svc" 180' "Direct VPS deploy health-gates rolling updates"
require_text "scripts/vps-direct-build-deploy.sh" 'app-a-next\|app-b-laravel\|sso-frontend' "Direct VPS deploy prewarms downstream apps before recreate"
require_text "scripts/vps-direct-build-deploy.sh" '--resolve "\$host:443:127\.0\.0\.1"' "Direct VPS deploy smokes HTTPS through the local reverse proxy"
require_text "scripts/vps-direct-build-deploy.sh" 'SMOKE_RETRIES' "Direct VPS deploy retries transient reverse-proxy smoke checks"
require_text "scripts/vps-direct-build-deploy.sh" 'Vue Admin Canary' "Direct VPS deploy smokes Vue canary"
require_text "scripts/vps-direct-build-deploy.sh" 'app_b_require_confidential_client_ready "deploy"' "Direct VPS deploy invokes shared App B confidential client guard"
require_text "scripts/vps-direct-build-deploy.sh" 'ZITADEL_VERSION' "Direct VPS deploy can rebuild the hosted ZITADEL login image"
require_text "scripts/vps-direct-build-deploy.sh" 'Zitadel Login Health' "Direct VPS deploy smokes hosted ZITADEL login health"
require_text "scripts/vps-direct-build-deploy.sh" 'prewarm_green_replicas' "Direct VPS deploy prewarms green replicas before Compose recreate"
require_text "scripts/vps-direct-build-deploy.sh" 'cleanup_green_for_service' "Direct VPS deploy removes temporary green replicas after health gate"
require_text "scripts/vps-direct-build-deploy.sh" 'GREEN_DRAIN_SECONDS' "Direct VPS deploy drains temporary green replicas before cleanup"
require_text "services/sso-frontend/src/web/styles/auth-shell-floating.css" 'position: fixed' "Vue auth shell toggle uses viewport edge floating host"
require_text "services/sso-frontend/src/web/styles/auth-shell-floating.css" '--theme-toggle-edge-right' "Vue auth shell toggle pins to the right safe area"
require_text "services/sso-frontend/src/web/styles/auth-shell-floating.css" 'justify-content: flex-end' "Vue auth shell toggle remains right-aligned when the host grows"
require_text "services/sso-frontend/src/web/styles/auth-shell-floating.css" '--theme-toggle-edge-bottom' "Vue auth shell toggle pins above the footer safe area"
require_text "infra/nginx/snippets/id-dev-sso-login-locale-reload.conf" 'parent-chrome\.js' "Nginx injects parent chrome fallback for direct ZITADEL login routes"
require_text "infra/nginx/assets/login/parent-chrome.css" 'bottom: max\(72px' "Nginx parent chrome fallback pins toggle to the bottom safe area"
require_text "infra/nginx/assets/login/parent-chrome.js" '__devssoToggleVersion' "Nginx parent chrome fallback exposes cache-bust version"
require_text "infra/nginx/assets/login/parent-chrome.js" '__devssoUrlPrivacyVersion' "Nginx parent chrome fallback redacts sensitive login query parameters"
require_text "infra/nginx/assets/login/parent-chrome.js" 'devssoLoginContext' "Nginx parent chrome fallback preserves auth flow context for submit"
require_text "infra/nginx/dev-sso.timeh.my.id.chained.conf" 'id_dev_sso_redact_login_name' "Nginx redacts loginName only after a flow request id exists"
require_text "infra/nginx/dev-sso.timeh.my.id.chained.conf" 'ui/v2/login/password' "Nginx keeps password-step login context intact"
require_text "infra/nginx/dev-sso.timeh.my.id.chained.conf" 'ui/v2/login/otp/' "Nginx keeps OTP-step login context intact"
require_text "infra/nginx/dev-sso.timeh.my.id.chained.conf" '"1:1:0"' "Nginx keeps login hints intact until ZITADEL consumes them"
require_text "infra/nginx/dev-sso.timeh.my.id.chained.conf" 'max-age=0, must-revalidate' "Nginx revalidates patched ZITADEL login assets without clearing cache"
require_text "infra/nginx/dev-sso.timeh.my.id.chained.conf" '/_devsso/login/parent-chrome\.js' "Nginx serves parent chrome fallback assets with explicit no-store route"

require_text "infra/terraform/environments/dev-sso/main.tf" 'zero_downtime_release_contract' "Terraform catalog captures zero-downtime release contract"
require_text "infra/terraform/environments/dev-sso/variables.tf" 'required_runtime_services' "Terraform catalog captures required runtime services"
require_text "infra/ansible/playbooks/devops-preflight.yml" 'Dev SSO VPS DevOps preflight' "Ansible has read-only VPS preflight playbook"
require_text "infra/ansible/playbooks/devops-preflight.yml" 'docker compose' "Ansible preflight checks Docker Compose"
require_text "infra/ansible/playbooks/devops-preflight.yml" '/\.well-known/openid-configuration' "Ansible preflight smokes OIDC discovery"
require_text "infra/ansible/playbooks/devops-preflight.yml" '/healthz' "Ansible preflight smokes Vue canary health"

require_text ".github/workflows/devops-lifecycle.yml" 'validate-devops-lifecycle\.sh' "DevOps workflow runs lifecycle validator"
require_text ".github/workflows/devops-lifecycle.yml" 'validate-sso-frontend-vue-lifecycle\.sh' "DevOps workflow validates rebuilt Vue SSO frontend"
require_text ".github/workflows/devops-lifecycle.yml" 'packages/dev-sso-parent-ui/\*\*' "DevOps workflow watches parent UI contract changes"
require_text ".github/workflows/devops-lifecycle.yml" 'services/sso-admin-vue/\*\*' "DevOps workflow watches Vue Admin lifecycle changes"
require_text ".github/workflows/devops-lifecycle.yml" 'hashicorp/setup-terraform@v4' "DevOps workflow validates Terraform"
require_text ".github/workflows/devops-lifecycle.yml" 'ansible-playbook --syntax-check' "DevOps workflow validates Ansible syntax"
require_text ".github/workflows/devops-lifecycle.yml" 'check-observability-assets\.sh' "DevOps workflow validates observability assets"
require_text ".github/workflows/devops-lifecycle.yml" 'check-secret-maturity\.sh' "DevOps workflow validates staged secret maturity"
require_text ".github/workflows/devops-lifecycle.yml" 'check-identity-resource-policy\.sh' "DevOps workflow validates identity resource isolation"
require_text "docker-compose.dev.yml" '^x-demo-web-limits:' "Compose declares constrained demo web runtime budget"
require_text "docker-compose.dev.yml" '^x-demo-php-limits:' "Compose declares constrained demo PHP runtime budget"
require_text "docker-compose.dev.yml" '^x-redis-limits:' "Compose declares dedicated Redis identity support budget"
require_text "docker-compose.dev.yml" 'cpu_shares: 2048' "Compose can prioritize identity data plane under CPU contention"
require_text "docker-compose.dev.yml" 'checkpoint_timeout=15min' "Compose spreads PostgreSQL checkpoint work for small-node efficiency"
require_text "docker-compose.dev.yml" 'max_parallel_workers=0' "Compose disables PostgreSQL parallel worker overhead on the 2-vCPU runtime"
require_text "docker-compose.dev.yml" 'jit=off' "Compose disables PostgreSQL JIT overhead for OLTP login traffic"
require_text "docker-compose.dev.yml" '--save[[:space:]]*$' "Compose keeps Redis from running duplicate RDB snapshots beside AOF"
require_text "docker-compose.dev.yml" '<<: \*demo-php-limits' "Compose applies constrained budget to demo PHP workload"
require_text "docker-compose.dev.yml" '<<: \*demo-web-limits' "Compose applies constrained budget to demo web workload"

warn_unless_text ".github/workflows/ci.yml" 'anchore/scan-action|trivy|grype|scan' "Container vulnerability scanning is integrated"
warn_unless_text ".github/workflows/devops-lifecycle.yml" 'kubeconform|helm lint|ct lint' "Kubernetes/Helm static validation is integrated"
warn_unless_text "infra/ansible/playbooks/devops-preflight.yml" 'firewall|ufw|nftables' "Host firewall automation is codified"
warn_unless_text "infra/terraform/environments/dev-sso/main.tf" 'dns|firewall|provider' "Provider-backed DNS/firewall resources are codified"

printf '[devops-lifecycle] Completed with %d failure(s), %d warning(s)\n' "$FAILURES" "$WARNINGS"

if (( FAILURES > 0 )); then
  exit 1
fi
